### ISSUE TITLE
issue with package slices required by pkg/wizgo

### ISSUE THREAD

**Issue by bwoznicki** [achetronic/wizgo#1]
There is a small issue with imports in pkg/wizgo resulting with error:

error while importing github.com/achetronic/wizgo/pkg/wizgo: package slices is not in GOROOT (/usr/local/go/src/slices)

**Comment by achetronic** [comment]
> There is a small issue with imports in pkg/wizgo resulting with error:
> 
> error while importing github.com/achetronic/wizgo/pkg/wizgo: package slices is not in GOROOT (/usr/local/go/src/slices)

Hello @bwoznicki can you gimme more context? How are you compiling, etc. It's to figure out the patch as it doesn't happen to me :)

**Comment by bwoznicki** [comment]
Sorry, ignore me, package slices is now part of the new standard lib I thought you are using the one from "golang.org/x/exp" and updating GO to version 1.23 fixed the problem...

**Comment by bwoznicki** [comment]
Fixed by updating GO to 1.23.3

**Comment by achetronic** [comment]
> Fixed by updating GO to 1.23.3

Hey, thank you for opening the issue. Then I will close it as solved 😊

**Comment by bwoznicki** [comment]
Hi spoke too early, there is an issue with that package...

go run .
github.com/achetronic/wizgo/pkg/wizgo
../../../go/pkg/mod/github.com/achetronic/wizgo@v0.1.0/pkg/wizgo/wizgo.go:9:2: could not import slices (open : no such file or directory)

The package slices did not exist before 1.21.3 in the standard lib so you must have used the one from golang.org/x/exp or have a local build of that package.

Also your go.mod specifies go 1.20 that package did not exist in that version of GO https://github.com/achetronic/wizgo/blob/9f2ef47906cfcd200af493896c1ed8779df24aa7/go.mod#L3

https://pkg.go.dev/slices@go1.21.3?tab=versions

**Comment by achetronic** [comment]
> Hi spoke too early, there is an issue with that package...
> 
> go run .
> github.com/achetronic/wizgo/pkg/wizgo
> ../../../go/pkg/mod/github.com/achetronic/wizgo@v0.1.0/pkg/wizgo/wizgo.go:9:2: could not import slices (open : no such file or directory)
> 
> The package slices did not exist before 1.21.3 in the standard lib so you must have used the one from golang.org/x/exp or have a local build of that package.
> 
> Also your go.mod specifies go 1.20 that package did not exist in that version of GO https://github.com/achetronic/wizgo/blob/9f2ef47906cfcd200af493896c1ed8779df24aa7/go.mod#L3
> 
> https://pkg.go.dev/slices@go1.21.3?tab=versions

Oh, the problem can be that the go.mod when I did the package is a bit different so missed upload it may be. Have you tested it specifying the version to 1.21?
